---
version: 0.2

branches:
  user/*, dev/*, q/*, w/*:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: docker
      path: eve/centos7
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
          haltOnFailure: True
# node-rdkafka installation seems mostly broken on Centos7 with given node version
# requires --force and manual node-gyp rebuild because ./configure is not launched automatically...
      - ShellCommand:
          name: install dependencies
          haltOnFailure: True
          command: npm install --force
      - ShellCommand:
          name: finish install node-rdkafka
          command: cd node_modules/node-rdkafka/ && ./configure && node-gyp rebuild
          haltOnFailure: True
      - ShellCommand:
          name: ESLint
          command: npm run lint
      - ShellCommand:
          name: JSDoc
          command: npm run jsdoc
      - ShellCommand:
          name: unit, functional tests with coverage
          command: npm run coverage tests/*
